"""
core/prevention.py
------------------
Prevention and mitigation recommendation engine.
Reads the latest root causes from the database and generates specific
actionable recommendations, which are also persisted to the database.
"""

import logging
import time
from typing import Dict, List

from database.db_manager import DatabaseManager
from config.settings import FAILURE_THRESHOLD, IGNORE_PROCESS_NAMES

logger = logging.getLogger(__name__)

# ── Recommendation templates ──────────────────────────────────────────────────
RECOMMENDATIONS = {
    "Memory Leak": [
        ("Restart the '{name}' process. This will free approximately {mem_pct:.1f}% of system memory.",                 "HIGH",    "Memory Leak"),
        ("Clear application cache and restart '{name}' to reclaim resources.",                   "MEDIUM",  "Memory Leak"),
        ("Increase available memory allocation limits for '{name}'.",        "MEDIUM",  "Memory Leak"),
        ("Profile the '{name}' process with a memory profiler to identify the exact leak site.", "LOW",   "Memory Leak"),
    ],
    "CPU Runaway": [
        ("Kill or restart the runaway '{name}' process immediately to restore CPU availability.",            "CRITICAL","CPU Runaway"),
        ("Optimize CPU-intensive algorithms in '{name}'.",    "HIGH",    "CPU Runaway"),
        ("Enable CPU affinity limits or cgroups to cap resource usage for '{name}'.",      "HIGH",    "CPU Runaway"),
        ("Review recent code changes to '{name}' that may have introduced a tight loop.", "MEDIUM","CPU Runaway"),
    ],
    "Thread Leak": [
        ("Restart the '{name}' process which is leaking threads.",                            "HIGH",    "Thread Leak"),
        ("Audit thread-pool configuration for the '{name}' service.",     "MEDIUM",  "Thread Leak"),
        ("Set maximum thread limits in the '{name}' configuration.",         "MEDIUM",  "Thread Leak"),
    ],
    "Resource Exhaustion": [
        ("Restart the underlying '{name}' service after draining active connections.",           "CRITICAL","Resource Exhaustion"),
        ("Increase file descriptor limits (ulimit -n) for '{name}'.",                    "HIGH",    "Resource Exhaustion"),
        ("Reduce connection pool sizes for '{name}'.",                   "HIGH",    "Resource Exhaustion"),
    ],
    "Disk Bottleneck": [
        ("Archive or delete old log files generated by '{name}' to free disk space.",             "HIGH",    "Disk Bottleneck"),
        ("Move high-write workloads for '{name}' to a faster storage tier (SSD/NVMe).", "MEDIUM",  "Disk Bottleneck"),
        ("Enable disk I/O scheduling tuning (elevator algorithm) for the volume used by '{name}'.",         "LOW",     "Disk Bottleneck"),
    ],
    "Network Bottleneck": [
        ("Review and throttle high-bandwidth network consumers, specifically '{name}'.",           "HIGH",    "Network Bottleneck"),
        ("Enable TCP buffer tuning before traffic reaches '{name}'.",       "MEDIUM",  "Network Bottleneck"),
        ("Assess upgrading network interface capacity used by '{name}'.",                    "LOW",     "Network Bottleneck"),
    ],
    "Normal Operation": [
        ("Continue monitoring – system is within healthy parameters.",      "LOW",     "Normal Operation"),
        ("Schedule a preventive system health review within 7 days.",       "LOW",     "Normal Operation"),
    ],
}

# Additional generic recommendations triggered by failure probability level
PROBABILITY_RECOMMENDATIONS = [
    (0.85, "CRITICAL failure probability detected – initiate emergency restart procedure.", "CRITICAL"),
    (0.65, "High failure probability – plan a controlled restart within the next hour.",    "HIGH"),
    (0.40, "Moderate failure risk – monitor closely and prepare restart runbook.",          "MEDIUM"),
    (0.15, "Low-level degradation detected – schedule maintenance at next opportunity.",    "LOW"),
]


class PreventionEngine:
    """
    Generates and stores prevention recommendations based on root cause results
    and current failure probability.
    """

    def __init__(self, db: DatabaseManager):
        self.db = db

    # ── Main entry point ──────────────────────────────────────────────────────

    def run(self) -> List[Dict]:
        """
        Generate recommendations from recent root causes and latest prediction.
        Persists all recommendations and returns the list.
        """
        now         = time.time()
        causes      = self.db.get_root_causes(limit=10)
        latest_pred = self.db.get_latest_prediction()
        recs: List[Dict] = []

        # Cause-specific recommendations (de-duplicate by text)
        seen_texts: set = set()
        ignore = {n.lower() for n in IGNORE_PROCESS_NAMES}
        for cause_row in causes:
            cause = cause_row.get("cause", "Normal Operation")
            name  = cause_row.get("name", "system")
            if name and name.lower() in ignore:
                continue
            templates = RECOMMENDATIONS.get(cause, [])
            
            # Look up memory footprint for the specific name
            mem_pct = 0.0
            if name and name != "system":
                latest = self.db.get_process_metrics_by_name(name, limit=1)
                if latest:
                    mem_pct = latest[0].get("memory", 0.0)

            for text_template, priority, related in templates:
                # Format the template with dynamic info
                try:
                    text = text_template.format(name=name, mem_pct=mem_pct)
                except KeyError:
                    text = text_template
                
                if text not in seen_texts:
                    seen_texts.add(text)
                    recs.append({
                        "timestamp":      now,
                        "recommendation": text,
                        "priority":       priority,
                        "related_cause":  related,
                    })

        # Probability-triggered recommendations
        if latest_pred:
            p = latest_pred.get("failure_probability", 0)
            for threshold, text, priority in PROBABILITY_RECOMMENDATIONS:
                if p >= threshold and text not in seen_texts:
                    seen_texts.add(text)
                    recs.append({
                        "timestamp":      now,
                        "recommendation": text,
                        "priority":       priority,
                        "related_cause":  "Failure Probability",
                    })
                    break  # Only the most severe probability message

        # Persist each recommendation
        for rec in recs:
            self.db.insert_recommendation(rec)

        logger.info("Prevention engine: %d recommendation(s) generated.", len(recs))
        return recs
